-- Calendar feed: one subscribable .ics URL per user, addressed by an unguessable token
-- because a calendar app cannot sign in through Cloudflare Access. The ICS text itself is
-- generated by the app (it already knows the schedule) and stored here verbatim.
CREATE TABLE IF NOT EXISTS cal_feeds (
  token      TEXT PRIMARY KEY,
  user       TEXT NOT NULL UNIQUE,
  ics        TEXT NOT NULL DEFAULT '',
  updated_at INTEGER NOT NULL
);
